language: csharp
solution: LibreMetaverse.sln

matrix:
  include:
    - os: linux # ubuntu 14.04
      dist: trusty
      sudo: required
      dotnet: 2.2.300
      mono: none
      script:
        - dotnet --info
        - dotnet restore
        - dotnet build --runtime linux-x64
    - os: osx # OSX 10.12
      osx_image: xcode9.2
      dotnet: 2.2.300
      mono: none
      script:
        - dotnet --info
        - dotnet restore
        - dotnet build --runtime osx10.12-x64
 